// apps/docs/src/registry/demos/ui/vue/button/shapes.vue
<script setup lang="ts">
import Button from '@/lib/components/vue/button.vue';
import { UploadIcon } from "@/lib/icons";
</script>

<template>
  <div className="flex items-center justify-center gap-4">
    <Button size="sm" shape="square" aria-label="upload">
      <UploadIcon />
    </Button>
    <Button size="md" shape="square" aria-label="upload">
      <UploadIcon />
    </Button>
    <Button size="lg" shape="square" aria-label="upload">
      <UploadIcon />
    </Button>
    <Button size="sm" shape="circle" aria-label="upload">
      <UploadIcon />
    </Button>
    <Button size="md" shape="circle" aria-label="upload">
      <UploadIcon />
    </Button>
    <Button size="lg" shape="circle" aria-label="upload">
      <UploadIcon />
    </Button>
  </div>
</template>

// apps/docs/src/registry/demos/ui/react/button/shapes.tsx
import { Button } from "@/registry/ui/react/button";
import { Upload } from "@/lib/icons";

export default function ButtonDemo() {
  return (
    <div className="flex items-center justify-center gap-4">
      <Button size="sm" shape="square" aria-label="upload">
        <Upload />
      </Button>
      <Button size="md" shape="square" aria-label="upload">
        <Upload />
      </Button>
      <Button size="lg" shape="square" aria-label="upload">
        <Upload />
      </Button>
      <Button size="sm" shape="circle" aria-label="upload">
        <Upload />
      </Button>
      <Button size="md" shape="circle" aria-label="upload">
        <Upload />
      </Button>
      <Button size="lg" shape="circle" aria-label="upload">
        <Upload />
      </Button>
    </div>
  );
}
