// apps/docs/src/registry/demos/ui/vue/button/sizes.vue
<script setup lang="ts">
import Button from '@/lib/components/vue/button.vue';
</script>

<template>
    <div className="flex w-full items-center justify-center gap-4">
      <Button size="sm">Button</Button>
      <Button size="md">Button</Button>
      <Button size="lg">Button</Button>
    </div>
</template>

// apps/docs/src/lib/demos/components/core/react/buttons/toggle/sizes.tsx
import { Toggle } from "@/lib/components/core/default/react/buttons/toggle";
import { Pin } from "@/lib/icons";

export default function ToggleDemo() {
  return (
    <div className="flex w-full items-center justify-center gap-4">
      <Toggle size="sm">
        <Pin />
      </Toggle>
      <Toggle size="md">
        <Pin />
      </Toggle>
      <Toggle size="lg">
        <Pin />
      </Toggle>
    </div>
  );
}
