// apps/docs/src/registry/ui/vue/skeleton.vue
<script setup lang="ts">
import { defineProps } from 'vue';
import { cn } from '@/lib/utils';

const props = defineProps({
  show: {
    type: Boolean,
    default: true,
  },
  class: {
    type: String,
    required: false,
  }
});
</script>

<template>
  <div v-if="!props.show">
    <slot />
  </div>

  <div
    v-else
    :class="cn(
      'relative block animate-pulse rounded-md bg-neutral',
      props.class
    )"
  >
    <div class="invisible">
      <slot />
    </div>
  </div>
</template>

// apps/docs/src/lib/components/core/default/react/feedback/skeleton.tsx
import { cn } from "@/lib/utils";

function Skeleton({
  className,
  show = true,
  ...props
}: React.HTMLAttributes<HTMLDivElement> & {
  show?: boolean;
}) {
  if (!show) return props.children;
  return (
    <span
      className={cn(
        "relative block h-6 animate-pulse rounded-md bg-neutral",
        props.children && "h-auto *:invisible",
        className,
      )}
      {...props}
    />
  );
}

export { Skeleton };
