// apps/docs/src/lib/components/core/default/react/feedback/skeleton.tsx
import { cn } from "@/lib/utils";

function Skeleton({
  className,
  show = true,
  ...props
}: React.HTMLAttributes<HTMLDivElement> & {
  show?: boolean;
}) {
  if (!show) return props.children;
  return (
    <span
      className={cn(
        "relative block h-6 animate-pulse rounded-md bg-neutral",
        props.children && "h-auto *:invisible",
        className,
      )}
      {...props}
    />
  );
}

export { Skeleton };

// apps/nuxt/shared/skeleton.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'
import { cn } from '~/lib/utils';

const props = defineProps({
    show: {
        type: Boolean,
        default: true
    },
    class: {
        type: String as HTMLAttributes['class'],
        required: false
    }
})
</script>

<template>
    <span :class="cn(
        'relative block h-6 animate-pulse rounded-md bg-neutral',
        props.show ? '' : 'invisible',
        props.class
    )">
        <slot v-if="!props.show" />
    </span>
</template>
