// apps/docs/src/registry/demos/ui/react/button/sizes.tsx
import { Button } from "@/registry/ui/react/button";

export default function ButtonDemo() {
  return (
    <div className="flex w-full items-center justify-center gap-4">
      <Button size="sm">Button</Button>
      <Button size="md">Button</Button>
      <Button size="lg">Button</Button>
    </div>
  );
}

// apps/docs/src/registry/demos/ui/vue/button/sizes.vue
<script setup lang="ts">
import Button from '@/lib/components/vue/button.vue';
</script>

<template>
    <div className="flex w-full items-center justify-center gap-4">
      <Button size="sm">Button</Button>
      <Button size="md">Button</Button>
      <Button size="lg">Button</Button>
    </div>
</template>
