// apps/docs/src/registry/demos/ui/react/button/variants.tsx
import { Button } from "@/registry/ui/react/button";

const variants = [
  "default",
  "primary",
  "secondary",
  "outline",
  "quiet",
  "success",
  "warning",
  "danger",
] as const;

export default function ButtonDemo() {
  return (
    <div className="grid grid-cols-4 gap-2">
      {variants.map((variant) => (
        <Button key={variant} variant={variant}>
          {variant}
        </Button>
      ))}
    </div>
  );
}

// apps/docs/src/registry/demos/ui/vue/button/variants.vue
<script setup lang="ts">
import Button from '@/lib/components/vue/button.vue';

const variants = [
  "default",
  "primary",
  "secondary",
  "outline",
  "quiet",
  "success",
  "warning",
  "danger",
] as const;
</script>


<template>
  <div class="grid grid-cols-4 gap-2">
    <Button v-for="variant in variants" :key="variant" :variant="variant">
      {{ variant }}
    </Button>
  </div>
</template>
