// apps/docs/src/registry/demos/ui/angular/button/loading.ts
import { Component } from "@angular/core";
import { HlmButtonModule } from "@/lib/components/angular/button/hlm-button.module";

@Component({
  selector: "button",
  standalone: true,
  imports: [HlmButtonModule],
  template: `
    <div className="flex w-full items-center justify-center gap-2">
      <Button hlmBtn [isLoading]="true" [size]="'sm'"> Button </Button>
      <Button hlmBtn [isLoading]="true" [size]="'md'"> Button </Button>
      <Button hlmBtn [isLoading]="true" [size]="'lg'"> Button </Button>
    </div>
  `,
})
export class ButtonPreviewComponent {}

// apps/docs/src/lib/demos/components/core/react/buttons/button/loading.tsx
import { Button } from "@/lib/components/core/default/react/buttons/button";

export default function ButtonDemo() {
  return (
    <div className="flex w-full items-center justify-center gap-2">
      <Button size="sm" isLoading>
        Button
      </Button>
      <Button size="md" isLoading>
        Button
      </Button>
      <Button size="lg" isLoading>
        Button
      </Button>
    </div>
  );
}
