// apps/docs/src/registry/demos/ui/vue/button/prefix-and-suffix.vue
<script setup lang="ts">
import Button from '@/lib/components/button.vue';
import { UploadIcon } from "@/lib/icons";
</script>

<template>
  <div className="flex items-center gap-2">
    <Button :prefix="UploadIcon">
      Button
    </Button>
    <Button :suffix="UploadIcon">
      Button
    </Button>
  </div>
</template>

// apps/docs/src/lib/demos/components/core/react/buttons/button/prefix-and-suffix.tsx
import { Button } from "@/lib/components/core/default/react/buttons/button";
import { UploadIcon } from "@/lib/icons";

export default function ButtonDemo() {
  return (
    <div className="flex items-center gap-2">
      <Button prefix={<UploadIcon />}>Upload</Button>
      <Button suffix={<UploadIcon />}>Upload</Button>
    </div>
  );
}
