// apps/docs/src/lib/demos/components/core/angular/buttons/button/prefix-and-suffix.ts
import { Component } from "@angular/core";
import { HlmButtonModule } from "@/lib/components/core/default/angular/button/hlm-button.module";
import { UploadIconComponent } from "@/lib/components/core/default/angular/lib/icons/icons";

@Component({
  selector: "button-preview",
  standalone: true,
  imports: [HlmButtonModule],
  template: `
    <div className="flex items-center gap-2">
      <Button hlmBtn [prefix]="UploadIconComponent"> Button </Button>
      <Button hlmBtn [suffix]="UploadIconComponent"> Button </Button>
    </div>
  `,
})
export class ButtonPreviewComponent {
  UploadIconComponent = UploadIconComponent;
}

// apps/docs/src/lib/demos/components/core/react/buttons/button/prefix-and-suffix.tsx
import { Button } from "@/lib/components/core/default/react/buttons/button";
import { Upload } from "@/lib/icons";

export default function ButtonDemo() {
  return (
    <div className="flex items-center gap-2">
      <Button prefix={<Upload />}>Upload</Button>
      <Button suffix={<Upload />}>Upload</Button>
    </div>
  );
}
