// apps/docs/src/lib/demos/components/core/angular/button/sizes.ts
import { Component } from "@angular/core";
import { HlmButtonModule } from "@/lib/components/core/default/angular/button/hlm-button.module";

@Component({
  selector: "button-preview",
  standalone: true,
  imports: [HlmButtonModule],
  template: `
    <div className="flex w-full items-center justify-center gap-4">
      <Button hlmBtn [size]="'sm'">Button</Button>
      <Button hlmBtn [size]="'md'">Button</Button>
      <Button hlmBtn [size]="'lg'">Button</Button>
    </div>
  `,
})
export class ButtonPreviewComponent {}

// apps/docs/src/lib/demos/components/core/react/buttons/button/sizes.tsx
import { Button } from "@/lib/components/core/default/react/buttons/button";

export default function ButtonDemo() {
  return (
    <div className="flex w-full items-center justify-center gap-4">
      <Button size="sm">Button</Button>
      <Button size="md">Button</Button>
      <Button size="lg">Button</Button>
    </div>
  );
}
